---
- name: Include OS and distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true

- name: Include common preflight tasks
  include_tasks: "common/preflight.yml"

- name: Include common provisioning tasks
  include_tasks: "common/{{ item }}.yml"
  with_items:
    - "install"
    - "config"
    - "launch"
    - "plugins"
